// frontends/solid/src/components/Alert.tsx
import type { JSX } from "solid-js";

type Variant = "info" | "success" | "danger";

const ICON: Record<Variant, string> = {
  info: "ⓘ",
  success: "✓",
  danger: "⚠",
};

export function Alert(props: {
  variant?: Variant;
  children: JSX.Element;
  style?: JSX.CSSProperties;
}) {
  const variant = () => props.variant ?? "info";
  return (
    <div class={`cy-alert cy-alert--${variant()}`} style={props.style}>
      <span>{ICON[variant()]}</span>
      <span>{props.children}</span>
    </div>
  );
}

// frontends/react-ts/src/components/Alert.tsx
import type { ReactNode } from "react";

type Variant = "info" | "success" | "danger";

const ICON: Record<Variant, string> = {
  info: "ⓘ",
  success: "✓",
  danger: "⚠",
};

export function Alert({
  variant = "info",
  children,
  style,
}: {
  variant?: Variant;
  children: ReactNode;
  style?: React.CSSProperties;
}) {
  return (
    <div className={`cy-alert cy-alert--${variant}`} style={style}>
      <span>{ICON[variant]}</span>
      <span>{children}</span>
    </div>
  );
}
