// fullstacks/nuxt/components/Alert.vue
<script setup lang="ts">
type Variant = "info" | "success" | "danger";

const props = withDefaults(
  defineProps<{ variant?: Variant }>(),
  { variant: "info" },
);

const ICON: Record<Variant, string> = {
  info: "ⓘ",
  success: "✓",
  danger: "⚠",
};
</script>

<template>
  <div :class="`cy-alert cy-alert--${props.variant}`">
    <span>{{ ICON[props.variant] }}</span>
    <span><slot /></span>
  </div>
</template>

// frontends/react-ts/src/components/Alert.tsx
import type { ReactNode } from "react";

type Variant = "info" | "success" | "danger";

const ICON: Record<Variant, string> = {
  info: "ⓘ",
  success: "✓",
  danger: "⚠",
};

export function Alert({
  variant = "info",
  children,
  style,
}: {
  variant?: Variant;
  children: ReactNode;
  style?: React.CSSProperties;
}) {
  return (
    <div className={`cy-alert cy-alert--${variant}`} style={style}>
      <span>{ICON[variant]}</span>
      <span>{children}</span>
    </div>
  );
}
