// frontends/svelte/src/components/AuthGate.svelte
<script lang="ts">
  // 路由守卫：未登录用户访问受保护页面时跳 /login?from=<currentPath>。
  // 已登录或拥有 refresh token 的状态都放行（refresh token 路径会自动 refresh）。

  import type { Snippet } from "svelte";
  import { navigate, useLocation } from "svelte-routing";
  import { authStore } from "@/stores/auth.svelte.ts";

  interface Props {
    children: Snippet;
  }

  let { children }: Props = $props();

  const location = useLocation();

  $effect(() => {
    if (!authStore.hydrated) return;
    if (authStore.user || authStore.refreshToken) return;
    const from = $location.pathname + $location.search;
    navigate(`/login?from=${encodeURIComponent(from)}`, { replace: true });
  });
</script>

{#if authStore.hydrated && (authStore.user || authStore.refreshToken)}
  {@render children()}
{/if}

// frontends/react-ts/src/components/AuthGate.tsx
import { Navigate, useLocation } from "react-router-dom";
import { useAuth } from "@/stores/auth";
import type { ReactNode } from "react";

// 路由守卫：未登录跳到 /login，并把当前 URL 放到 state 里以便登录后回跳
export function AuthGate({ children }: { children: ReactNode }) {
  const user = useAuth((s) => s.user);
  const hydrated = useAuth((s) => s.hydrated);
  const refreshToken = useAuth((s) => s.refreshToken);
  const location = useLocation();

  if (!hydrated) return null;

  // 有 user 直接通过；只有 refreshToken（刷新页未拿到 access）也允许进入，
  // 接口调用会自动 refresh
  if (user || refreshToken) return <>{children}</>;

  return <Navigate to="/login" replace state={{ from: location.pathname }} />;
}
