// frontends/svelte/src/components/FavoriteButton.svelte
<script lang="ts">
  import { navigate, useLocation } from "svelte-routing";
  import { authStore } from "@/stores/auth.svelte.ts";
  import { plazaStore } from "@/stores/plaza.svelte.ts";
  import { api } from "@/api/client";
  import { ApiError } from "@/types";
  import type { CapsuleListItem, CapsuleDetail } from "@/types";

  interface Props {
    capsule: Pick<
      CapsuleListItem | CapsuleDetail,
      "id" | "favoritedByMe" | "favoriteCount"
    >;
    size?: "sm" | "md";
    onChange?: (favorited: boolean, count: number) => void;
  }

  let { capsule, size = "sm", onChange }: Props = $props();

  const location = useLocation();

  let active = $state(false);
  let count = $state(0);
  let busy = $state(false);
  let err = $state<string | null>(null);

  // 把 props 拍到本地 state：挂载时初始化，capsule 切换时同步。
  // 父组件如果做了乐观更新（patchFavorited 后回写新对象），这里也会跟着刷新。
  $effect(() => {
    active = capsule.favoritedByMe;
    count = capsule.favoriteCount;
  });

  const favoriteColor = $derived(
    active
      ? "var(--color-favorite-active)"
      : "var(--color-favorite-inactive)",
  );

  async function toggle() {
    err = null;

    if (!authStore.user) {
      // 匿名用户：跳登录，带上当前页路径以便登录后回来
      const yes = window.confirm("登录后才能收藏，前往登录？");
      if (yes) {
        const from = encodeURIComponent($location.pathname + $location.search);
        navigate(`/login?from=${from}`);
      }
      return;
    }

    busy = true;
    try {
      if (active) {
        await api.unfavorite(capsule.id);
        const next = Math.max(0, count - 1);
        active = false;
        count = next;
        plazaStore.patchFavorited(capsule.id, false, next);
        onChange?.(false, next);
      } else {
        const r = await api.favorite(capsule.id);
        active = true;
        count = r.favoriteCount;
        plazaStore.patchFavorited(capsule.id, true, r.favoriteCount);
        onChange?.(true, r.favoriteCount);
      }
    } catch (e) {
      err = e instanceof ApiError ? e.message : "操作失败";
    } finally {
      busy = false;
    }
  }
</script>

{#if size === "md"}
  <button
    type="button"
    class={["cy-btn", "cy-btn--accent", active ? "is-active" : ""].join(" ")}
    disabled={busy}
    title={err ?? undefined}
    onclick={toggle}
  >
    <span style:color={favoriteColor}>{active ? "♥" : "♡"}</span>
    收藏 · {count}
  </button>
{:else}
  <button
    type="button"
    class={["cy-capsule__fav", active ? "is-active" : ""].join(" ")}
    disabled={busy}
    title={err ?? undefined}
    onclick={toggle}
  >
    {active ? "♥" : "♡"} {count}
  </button>
{/if}

// frontends/react-ts/src/components/FavoriteButton.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/stores/auth";
import { usePlaza } from "@/stores/plaza";
import { api } from "@/api/client";
import { ApiError, type CapsuleListItem, type CapsuleDetail } from "@/types";

interface Props {
  capsule: Pick<
    CapsuleListItem | CapsuleDetail,
    "id" | "favoritedByMe" | "favoriteCount"
  >;
  size?: "sm" | "md";
  onChange?: (favorited: boolean, count: number) => void;
}

export function FavoriteButton({ capsule, size = "sm", onChange }: Props) {
  const user = useAuth((s) => s.user);
  const navigate = useNavigate();
  const patchPlaza = usePlaza((s) => s.patchFavorited);

  const [active, setActive] = useState(capsule.favoritedByMe);
  const [count, setCount] = useState(capsule.favoriteCount);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  async function toggle() {
    setErr(null);

    if (!user) {
      // 匿名用户：跳登录提示，而不是静默失败
      const yes = window.confirm("登录后才能收藏，前往登录？");
      if (yes) navigate("/login");
      return;
    }

    setBusy(true);
    try {
      if (active) {
        await api.unfavorite(capsule.id);
        const next = Math.max(0, count - 1);
        setActive(false);
        setCount(next);
        patchPlaza(capsule.id, false, next);
        onChange?.(false, next);
      } else {
        const r = await api.favorite(capsule.id);
        setActive(true);
        setCount(r.favoriteCount);
        patchPlaza(capsule.id, true, r.favoriteCount);
        onChange?.(true, r.favoriteCount);
      }
    } catch (e) {
      setErr(e instanceof ApiError ? e.message : "操作失败");
    } finally {
      setBusy(false);
    }
  }

  if (size === "md") {
    return (
      <button
        type="button"
        className={`cy-btn cy-btn--accent ${active ? "is-active" : ""}`}
        onClick={toggle}
        disabled={busy}
        title={err ?? undefined}
      >
        <span style={{ color: active ? "var(--color-favorite-active)" : "var(--color-favorite-inactive)" }}>
          {active ? "♥" : "♡"}
        </span>
        收藏 · {count}
      </button>
    );
  }

  return (
    <button
      type="button"
      className={`cy-capsule__fav ${active ? "is-active" : ""}`}
      onClick={toggle}
      disabled={busy}
      title={err ?? undefined}
    >
      {active ? "♥" : "♡"} {count}
    </button>
  );
}
