// frontends/vue3-ts/src/components/MeLayout.vue
<script setup lang="ts">
import AppHeader from "./AppHeader.vue";
import AppFooter from "./AppFooter.vue";
import { useAuthStore } from "@/stores/auth";

const auth = useAuthStore();

async function handleLogout(e: MouseEvent) {
  e.preventDefault();
  await auth.logout();
  window.location.assign("/");
}
</script>

<template>
  <AppHeader />
  <main class="cy-container">
    <div class="cy-me">
      <aside class="cy-me__nav">
        <RouterLink to="/me/created" active-class="is-active">📝 我创建的</RouterLink>
        <RouterLink to="/me/favorites" active-class="is-active">♥ 我收藏的</RouterLink>
        <RouterLink to="/me/profile" active-class="is-active">⚙ 账号设置</RouterLink>
        <span style="border-top:1px solid var(--color-border-subtle);margin:var(--space-3) 0" />
        <a
          href="/login"
          style="color: var(--color-danger-fg)"
          @click="handleLogout"
        >登出</a>
      </aside>
      <section class="cy-me__content">
        <RouterView />
      </section>
    </div>
  </main>
  <AppFooter />
</template>

// frontends/solid/src/components/MeLayout.tsx
import type { JSX } from "solid-js";
import { A } from "@solidjs/router";
import { logout } from "@/stores/auth";
import { AppHeader } from "./AppHeader";
import { AppFooter } from "./AppFooter";

export function MeLayout(props: { children?: JSX.Element }) {
  return (
    <>
      <AppHeader />
      <main class="cy-container">
        <div class="cy-me">
          <aside class="cy-me__nav">
            <A href="/me/created" activeClass="is-active">
              📝 我创建的
            </A>
            <A href="/me/favorites" activeClass="is-active">
              ♥ 我收藏的
            </A>
            <A href="/me/profile" activeClass="is-active">
              ⚙ 账号设置
            </A>
            <span
              style={{
                "border-top": "1px solid var(--color-border-subtle)",
                margin: "var(--space-3) 0",
              }}
            />
            <a
              href="/login"
              onClick={(e) => {
                e.preventDefault();
                void logout().then(() => window.location.assign("/"));
              }}
              style={{ color: "var(--color-danger-fg)" }}
            >
              登出
            </a>
          </aside>
          <section class="cy-me__content">{props.children}</section>
        </div>
      </main>
      <AppFooter />
    </>
  );
}
