// frontends/react-ts/src/components/AvatarPicker.tsx
import type { Avatar } from "@/types";
import { avatarUrl } from "@/utils/avatar";

interface Props {
  avatars: Avatar[];
  value: string | null;
  onChange: (id: string) => void;
}

export function AvatarPicker({ avatars, value, onChange }: Props) {
  return (
    <div className="cy-avatar-picker" role="radiogroup" aria-label="选择头像">
      {avatars.map((a) => (
        <button
          key={a.id}
          type="button"
          role="radio"
          aria-checked={value === a.id}
          className={`cy-avatar-picker__item ${value === a.id ? "is-selected" : ""}`}
          onClick={() => onChange(a.id)}
          title={a.name}
        >
          <img src={a.svgUrl ?? avatarUrl(a.id)} alt={a.name} />
        </button>
      ))}
    </div>
  );
}

// fullstacks/nuxt/components/AvatarPicker.vue
<script setup lang="ts">
import type { Avatar } from "@/types";
import { avatarUrl } from "@/utils/avatar";

defineProps<{
  avatars: Avatar[];
  modelValue: string | null;
}>();

defineEmits<{
  (e: "update:modelValue", id: string): void;
}>();
</script>

<template>
  <div class="cy-avatar-picker" role="radiogroup" aria-label="选择头像">
    <button
      v-for="a in avatars"
      :key="a.id"
      type="button"
      role="radio"
      :aria-checked="modelValue === a.id"
      :class="['cy-avatar-picker__item', modelValue === a.id ? 'is-selected' : '']"
      :title="a.name"
      @click="$emit('update:modelValue', a.id)"
    >
      <img :src="a.svgUrl ?? avatarUrl(a.id)" :alt="a.name" />
    </button>
  </div>
</template>
