// frontends/react-ts/src/components/ThemeToggle.tsx
import { useTheme } from "@/stores/theme";

export function ThemeToggle() {
  const theme = useTheme((s) => s.theme);
  const toggle = useTheme((s) => s.toggle);
  return (
    <button
      type="button"
      className="cy-theme-toggle"
      aria-label="切换主题"
      onClick={toggle}
    >
      <span aria-hidden="true">{theme === "dark" ? "☾" : "☀"}</span>
    </button>
  );
}

// fullstacks/nuxt/components/ThemeToggle.vue
<script setup lang="ts">
import { storeToRefs } from "pinia";
import { useThemeStore } from "@/stores/theme";

const store = useThemeStore();
const { theme } = storeToRefs(store);
</script>

<template>
  <button
    type="button"
    class="cy-theme-toggle"
    aria-label="切换主题"
    @click="store.toggle()"
  >
    <span aria-hidden="true">{{ theme === "dark" ? "☾" : "☀" }}</span>
  </button>
</template>
