// frontends/angular/src/app/components/theme-toggle/theme-toggle.component.ts
import { Component, inject } from '@angular/core';
import { ThemeStore } from '@/stores/theme.store';

@Component({
  selector: 'app-theme-toggle',
  standalone: true,
  template: `
    <button type="button" class="cy-theme-toggle" aria-label="切换主题" (click)="theme.toggle()">
      <span aria-hidden="true">{{ theme.theme() === 'dark' ? '☾' : '☀' }}</span>
    </button>
  `,
})
export class ThemeToggleComponent {
  theme = inject(ThemeStore);
}

// fullstacks/nuxt/components/ThemeToggle.vue
<script setup lang="ts">
import { storeToRefs } from "pinia";
import { useThemeStore } from "@/stores/theme";

const store = useThemeStore();
const { theme } = storeToRefs(store);
</script>

<template>
  <button
    type="button"
    class="cy-theme-toggle"
    aria-label="切换主题"
    @click="store.toggle()"
  >
    <span aria-hidden="true">{{ theme === "dark" ? "☾" : "☀" }}</span>
  </button>
</template>
