// frontends/svelte/src/App.svelte
<script lang="ts">
  import { Router, Route } from "svelte-routing";
  import MainLayout from "@/components/MainLayout.svelte";
  import MeLayout from "@/components/MeLayout.svelte";
  import AuthGate from "@/components/AuthGate.svelte";

  import PlazaPage from "@/pages/PlazaPage.svelte";
  import OpenPage from "@/pages/OpenPage.svelte";
  import AboutPage from "@/pages/AboutPage.svelte";
  import LoginPage from "@/pages/LoginPage.svelte";
  import RegisterPage from "@/pages/RegisterPage.svelte";
  import CreatePage from "@/pages/CreatePage.svelte";
  import CapsuleByCodePage from "@/pages/CapsuleByCodePage.svelte";
  import MeCreatedPage from "@/pages/MeCreatedPage.svelte";
  import MeFavoritesPage from "@/pages/MeFavoritesPage.svelte";
  import MeProfilePage from "@/pages/MeProfilePage.svelte";
  import NotFoundPage from "@/pages/NotFoundPage.svelte";

  import { authStore } from "@/stores/auth.svelte.ts";
  import { themeStore } from "@/stores/theme.svelte.ts";

  // 应用启动时 hydrate theme / auth；
  // 若本地有 refresh token 但还没拿到完整 user，则主动拉一次 /me 校验登录态。
  // 注意：hydrate 只跑一次，所以放在 onMount-like 的 $effect.root 替代里更稳妥；
  // 这里用 $effect 因为只在客户端 mount 后执行。
  $effect(() => {
    themeStore.hydrate();
    authStore.hydrate();
  });

  $effect(() => {
    if (authStore.hydrated && authStore.refreshToken && !authStore.user) {
      void authStore.refreshMe();
    }
  });
</script>

<Router>
  <Route path="/"><MainLayout><PlazaPage /></MainLayout></Route>
  <Route path="/open"><MainLayout><OpenPage /></MainLayout></Route>
  <Route path="/about"><MainLayout><AboutPage /></MainLayout></Route>
  <Route path="/login"><MainLayout><LoginPage /></MainLayout></Route>
  <Route path="/register"><MainLayout><RegisterPage /></MainLayout></Route>
  <Route path="/create">
    <MainLayout><AuthGate><CreatePage /></AuthGate></MainLayout>
  </Route>
  <Route path="/c/:code" let:params>
    <MainLayout><CapsuleByCodePage code={params.code} /></MainLayout>
  </Route>

  <Route path="/me">
    <MeLayout><AuthGate><MeCreatedPage /></AuthGate></MeLayout>
  </Route>
  <Route path="/me/created">
    <MeLayout><AuthGate><MeCreatedPage /></AuthGate></MeLayout>
  </Route>
  <Route path="/me/favorites">
    <MeLayout><AuthGate><MeFavoritesPage /></AuthGate></MeLayout>
  </Route>
  <Route path="/me/profile">
    <MeLayout><AuthGate><MeProfilePage /></AuthGate></MeLayout>
  </Route>

  <!-- 兜底：未匹配到任何路径 -->
  <Route><MainLayout><NotFoundPage /></MainLayout></Route>
</Router>

// frontends/solid/src/App.tsx
import { createEffect, onMount, untrack, type JSX } from "solid-js";
import { Router, Route, Navigate } from "@solidjs/router";
import { MainLayout } from "@/components/MainLayout";
import { MeLayout } from "@/components/MeLayout";
import { AuthGate } from "@/components/AuthGate";
import { auth, hydrateAuth, refreshMe } from "@/stores/auth";
import { hydrateTheme } from "@/stores/theme";

import { PlazaPage } from "@/pages/PlazaPage";
import { OpenPage } from "@/pages/OpenPage";
import { AboutPage } from "@/pages/AboutPage";
import { LoginPage } from "@/pages/LoginPage";
import { RegisterPage } from "@/pages/RegisterPage";
import { CreatePage } from "@/pages/CreatePage";
import { CapsuleByCodePage } from "@/pages/CapsuleByCodePage";
import { MeCreatedPage } from "@/pages/MeCreatedPage";
import { MeFavoritesPage } from "@/pages/MeFavoritesPage";
import { MeProfilePage } from "@/pages/MeProfilePage";
import { NotFoundPage } from "@/pages/NotFoundPage";

// 受保护的个人中心布局：守卫 + 布局 + 子路由 outlet
function MeShell(props: { children?: JSX.Element }) {
  return (
    <AuthGate>
      <MeLayout>{props.children}</MeLayout>
    </AuthGate>
  );
}

export function App() {
  onMount(() => {
    hydrateTheme();
    hydrateAuth();
  });

  // 一旦完成 hydrate，且本地有 refresh token 但还没拿到完整 user 信息（!auth.user），
  // 主动拉一次 /me 验证登录态。加 !auth.user 避免登录 setTokens / token 轮换改动 refreshToken
  // 时重复触发 /me；用 untrack 包住调用，确保 refreshMe 内部读取不被纳入本 effect 依赖。
  createEffect(() => {
    if (auth.hydrated && auth.refreshToken && !auth.user) {
      untrack(() => void refreshMe());
    }
  });

  return (
    <Router>
      <Route component={MainLayout}>
        <Route path="/" component={PlazaPage} />
        <Route path="/open" component={OpenPage} />
        <Route path="/about" component={AboutPage} />
        <Route path="/login" component={LoginPage} />
        <Route path="/register" component={RegisterPage} />
        <Route
          path="/create"
          component={() => (
            <AuthGate>
              <CreatePage />
            </AuthGate>
          )}
        />
        <Route path="/c/:code" component={CapsuleByCodePage} />
      </Route>
      <Route component={MeShell}>
        <Route path="/me" component={() => <Navigate href="/me/created" />} />
        <Route path="/me/created" component={MeCreatedPage} />
        <Route path="/me/favorites" component={MeFavoritesPage} />
        <Route path="/me/profile" component={MeProfilePage} />
      </Route>
      <Route path="*" component={NotFoundPage} />
    </Router>
  );
}
