// frontends/react-ts/src/components/Alert.tsx
import type { ReactNode } from "react";

type Variant = "info" | "success" | "danger";

const ICON: Record<Variant, string> = {
  info: "ⓘ",
  success: "✓",
  danger: "⚠",
};

export function Alert({
  variant = "info",
  children,
  style,
}: {
  variant?: Variant;
  children: ReactNode;
  style?: React.CSSProperties;
}) {
  return (
    <div className={`cy-alert cy-alert--${variant}`} style={style}>
      <span>{ICON[variant]}</span>
      <span>{children}</span>
    </div>
  );
}

// frontends/svelte/src/components/Alert.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  type Variant = "info" | "success" | "danger";

  interface Props {
    variant?: Variant;
    children: Snippet;
  }

  let { variant = "info", children }: Props = $props();

  const ICON: Record<Variant, string> = {
    info: "ⓘ",
    success: "✓",
    danger: "⚠",
  };
</script>

<div class={`cy-alert cy-alert--${variant}`}>
  <span>{ICON[variant]}</span>
  <span>{@render children()}</span>
</div>
