// frontends/react-ts/src/App.tsx
import { useEffect } from "react";
import { RouterProvider } from "react-router-dom";
import { router } from "@/router";
import { useAuth } from "@/stores/auth";
import { useTheme } from "@/stores/theme";

export function App() {
  const hydrateAuth = useAuth((s) => s.hydrate);
  const refreshMe = useAuth((s) => s.refreshMe);
  const hydrated = useAuth((s) => s.hydrated);
  const refreshToken = useAuth((s) => s.refreshToken);
  const hydrateTheme = useTheme((s) => s.hydrate);

  useEffect(() => {
    hydrateTheme();
    hydrateAuth();
  }, [hydrateAuth, hydrateTheme]);

  // 一旦完成 hydrate，且本地有 refresh token 但还没拿到完整 user 信息，
  // 主动拉一次 /me 验证登录态
  useEffect(() => {
    if (hydrated && refreshToken) {
      void refreshMe();
    }
  }, [hydrated, refreshToken, refreshMe]);

  return <RouterProvider router={router} />;
}

// frontends/angular/src/app/app.component.ts
import { Component, effect, inject, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { AuthStore } from '@/stores/auth.store';
import { ThemeStore } from '@/stores/theme.store';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `<router-outlet />`,
})
export class AppComponent implements OnInit {
  private auth = inject(AuthStore);
  private theme = inject(ThemeStore);

  constructor() {
    // 水合完成且有 refresh token 时，主动拉一次 /me 验证登录态
    effect(() => {
      if (this.auth.hydrated() && this.auth.refreshToken()) {
        void this.auth.refreshMe();
      }
    });
  }

  ngOnInit() {
    this.theme.hydrate();
    // auth store 的 hydrate 在 withHooks.onInit 中已自动触发
  }
}
