// mobile/react-native/src/app/about.tsx
// 关于：移植自 frontends/react-ts/src/pages/AboutPage.tsx。
// 产品简介 + 移动端（RN）技术栈 + 后端技术栈（from /health）+ 后端连通点。

import { useEffect, useState } from "react";
import { Pressable, View } from "react-native";
import { useRouter } from "expo-router";
import { api } from "@/api/client";
import { API_BASE } from "@/api/config";
import type { HealthData, StackItem } from "@/types";
import { fontSize, radius, space, usePalette } from "@/theme";
import { Alert, Card, Screen, T } from "@/components/ui";
import { RemoteSvg } from "@/components/media";

const MOBILE_STACK: StackItem[] = [
  { role: "framework", name: "React Native", version: "0.85", iconUrl: "/static/icons/react.svg" },
  { role: "toolchain", name: "Expo", version: "56", iconUrl: null },
  { role: "language", name: "TypeScript", version: "6", iconUrl: "/static/icons/typescript.svg" },
];

const MOBILE_SUMMARY =
  "基于 Expo（SDK 56）+ React Native + TypeScript：Expo Router 文件式路由驱动底部 Tab Bar 导航，" +
  "Zustand 做轻量状态管理，业务逻辑（JWT 刷新 / 收藏计数 / 胶囊开启判定）与类型契约直接复用 Web React 前端。" +
  "与之对照，frontends/react-ts 把同一套 store/api/types 渲染成 DOM，而本端渲染成原生组件 —— " +
  "即「Web React vs Native React」：逻辑/令牌共享，视图层分叉。设计令牌经 codegen 从 tokens.json 落地为 RN 的 tokens.ts。";

function resolveIcon(u: string): string {
  return u.startsWith("http") ? u : `${API_BASE}${u}`;
}

function IconRow({ items }: { items: StackItem[] }) {
  const pal = usePalette();
  return (
    <View style={{ flexDirection: "row", gap: space[6], flexWrap: "wrap", marginBottom: space[3] }}>
      {items.map((it) => (
        <View key={it.name} style={{ alignItems: "center", gap: space[1] }}>
          {it.iconUrl ? (
            <RemoteSvg uri={resolveIcon(it.iconUrl)} size={40} />
          ) : (
            <View style={{ width: 40, height: 40, backgroundColor: pal.surface[2], borderRadius: radius.md }} />
          )}
          <T tone="muted" size={fontSize.xs} mono>
            {it.name}
            {it.version ? ` ${it.version}` : ""}
          </T>
        </View>
      ))}
    </View>
  );
}

export default function AboutScreen() {
  const router = useRouter();
  const [health, setHealth] = useState<HealthData | null>(null);
  const [connected, setConnected] = useState<boolean | null>(null);

  useEffect(() => {
    let alive = true;
    api
      .health()
      .then((d) => {
        if (alive) {
          setHealth(d);
          setConnected(true);
        }
      })
      .catch(() => {
        if (alive) setConnected(false);
      });
    return () => {
      alive = false;
    };
  }, []);

  const pal = usePalette();
  const backendItems = health
    ? [...health.stack.items].sort((a, b) => {
        const order = ["framework", "language", "database"];
        return order.indexOf(a.role) - order.indexOf(b.role);
      })
    : [];
  const backendFramework = health?.stack.items.find((it) => it.role === "framework")?.name ?? "—";
  const dot = connected === true ? pal.success.solid : connected === false ? pal.danger.solid : pal.text.muted;

  return (
    <Screen scroll contentStyle={{ gap: space[6] }}>
      <Pressable onPress={() => (router.canGoBack() ? router.back() : router.replace("/"))} hitSlop={8}>
        <T tone="signal">‹ 返回</T>
      </Pressable>

      <T display weight="700" size={fontSize["3xl"]}>
        关于 <T display weight="700" size={fontSize["3xl"]} tone="signal">HelloTime Pro</T>
      </T>

      <T tone="secondary" size={fontSize.base} style={{ lineHeight: fontSize.base * 1.7 }}>
        一款时光胶囊应用——写下一段话，设定未来某刻才能开启，内容上锁后不可修改。
        同时也是一个多技术栈对比学习项目：同一份产品需求由多套前后端 / 客户端各自实现，
        共享同一份 API 契约、数据库 schema 与设计 token。
      </T>

      <View style={{ gap: space[3] }}>
        <T display weight="600" size={fontSize.xl}>
          移动端技术栈
        </T>
        <Card style={{ gap: space[2] }}>
          <IconRow items={MOBILE_STACK} />
          <T tone="secondary" size={fontSize.sm} style={{ lineHeight: fontSize.sm * 1.7 }}>
            {MOBILE_SUMMARY}
          </T>
        </Card>
      </View>

      {connected === false ? <Alert variant="danger">无法读取后端信息，请确认后端已在 {API_BASE} 运行。</Alert> : null}

      {health ? (
        <View style={{ gap: space[3] }}>
          <T display weight="600" size={fontSize.xl}>
            后端技术栈
          </T>
          <Card style={{ gap: space[2] }}>
            <IconRow items={backendItems} />
            <T tone="secondary" size={fontSize.sm} style={{ lineHeight: fontSize.sm * 1.7 }}>
              {health.stack.summary}
            </T>
          </Card>
        </View>
      ) : null}

      <View style={{ flexDirection: "row", alignItems: "center", gap: space[2], flexWrap: "wrap" }}>
        <View style={{ width: 8, height: 8, borderRadius: 4, backgroundColor: dot }} />
        <T tone="muted" size={fontSize.sm}>
          后端 {connected === true ? "在线" : connected === false ? "离线" : "连接中…"} · {backendFramework} · License: MIT
        </T>
      </View>
    </Screen>
  );
}

// fullstacks/nuxt/pages/about.vue
<script setup lang="ts">
import { computed } from "vue";
import { api } from "@/api/client";
import Alert from "@/components/Alert.vue";
import type { HealthData, StackItem } from "@/types";

const APP_STACK: StackItem[] = [
  { role: "framework", name: "Nuxt",         version: "3", iconUrl: "/static/icons/nuxt.svg" },
  { role: "view",      name: "Vue",          version: "3", iconUrl: "/static/icons/vue.svg" },
  { role: "language",  name: "TypeScript",   version: "5", iconUrl: "/static/icons/typescript.svg" },
  { role: "styling",   name: "Tailwind CSS", version: "4", iconUrl: "/static/icons/tailwindcss.svg" },
];

const APP_SUMMARY =
  "基于 Nuxt 3 pages/layouts 组织路由与页面，Vue 3 Composition API + <script setup> 聚合交互逻辑，" +
  "Pinia 管理 auth、theme、plaza 三个状态域，Nitro server/api 提供同源 REST 接口，" +
  "样式通过 Tailwind CSS v4 语义 token 统一约束。";

const { data: health, error } = await useAsyncData<HealthData>("health", () => api.health(), {
  server: false,
});
const errorText = computed(() => (error.value ? String(error.value) : null));

const backendItems = computed<StackItem[]>(() => {
  if (!health.value) return [];
  const order = ["framework", "language", "database"];
  return [...health.value.stack.items].sort(
    (a, b) => order.indexOf(a.role) - order.indexOf(b.role),
  );
});

const backendFramework = computed(
  () => health.value?.stack.items.find((it) => it.role === "framework")?.name ?? "—",
);
</script>

<template>
  <main
    class="cy-container cy-container--narrow"
    style="margin: var(--space-12) auto var(--space-16)"
  >
    <!-- 标题 -->
    <h1 style="font-family: var(--font-display); font-size: var(--font-size-5xl); margin: 0 0 var(--space-3)">
      关于
      <span style="background: var(--gradient-brand-hero); -webkit-background-clip: text; background-clip: text; color: transparent">
        HelloTime Pro
      </span>
    </h1>

    <!-- 产品简介 -->
    <p style="color: var(--color-text-secondary); font-size: var(--font-size-lg); line-height: var(--line-height-relaxed); margin: 0 0 var(--space-10)">
      一款时光胶囊 Web 应用——写下一段话，设定未来某刻才能开启，内容上锁后不可修改。
      支持胶囊广场浏览、AI 辅助创作、收藏与账户管理。同时也是一个多技术栈对比学习项目，
      同一份产品需求由多套前后端框架各自实现，共享同一份 API 契约、数据库 schema 与设计 token。
    </p>

    <!-- 应用技术栈 -->
    <section style="margin-bottom: var(--space-10)">
      <h2 style="font-family: var(--font-display); font-size: var(--font-size-2xl); margin: 0 0 var(--space-5)">
        应用技术栈
      </h2>
      <div class="cy-card" style="padding: var(--space-6)">
        <!-- 图标行 -->
        <div style="display: flex; gap: var(--space-6); flex-wrap: wrap; margin-bottom: var(--space-4)">
          <div
            v-for="it in APP_STACK"
            :key="it.name"
            style="display: flex; flex-direction: column; align-items: center; gap: var(--space-1)"
          >
            <img v-if="it.iconUrl" :src="it.iconUrl" :alt="it.name" style="width: 48px; height: 48px" />
            <div v-else style="width: 48px; height: 48px; background: var(--color-surface-2); border-radius: var(--radius-md)" />
            <span style="font-size: var(--font-size-xs); color: var(--color-text-muted); font-family: var(--font-mono)">
              {{ it.name }}
            </span>
          </div>
        </div>
        <p style="margin: 0; color: var(--color-text-secondary); line-height: var(--line-height-relaxed)">
          {{ APP_SUMMARY }}
        </p>
      </div>
    </section>

    <!-- 服务端技术栈 -->
    <Alert v-if="errorText" variant="danger" style="margin-bottom: var(--space-6)">
      无法读取服务端信息：{{ errorText }}
    </Alert>

    <section v-if="health" style="margin-bottom: var(--space-10)">
      <h2 style="font-family: var(--font-display); font-size: var(--font-size-2xl); margin: 0 0 var(--space-5)">
        服务端技术栈
      </h2>
      <div class="cy-card" style="padding: var(--space-6)">
        <!-- 图标行（动态） -->
        <div style="display: flex; gap: var(--space-6); flex-wrap: wrap; margin-bottom: var(--space-4)">
          <div
            v-for="it in backendItems"
            :key="it.name"
            style="display: flex; flex-direction: column; align-items: center; gap: var(--space-1)"
          >
            <img v-if="it.iconUrl" :src="it.iconUrl" :alt="it.name" style="width: 48px; height: 48px" />
            <div v-else style="width: 48px; height: 48px; background: var(--color-surface-2); border-radius: var(--radius-md)" />
            <span style="font-size: var(--font-size-xs); color: var(--color-text-muted); font-family: var(--font-mono)">
              {{ it.name }}
            </span>
          </div>
        </div>
        <p style="margin: 0; color: var(--color-text-secondary); line-height: var(--line-height-relaxed)">
          {{ health.stack.summary }}
        </p>
      </div>
    </section>

    <!-- 底部元信息 -->
    <div style="padding: var(--space-4) 0; border-top: 1px solid var(--color-border-subtle); color: var(--color-text-muted); font-size: var(--font-size-sm); display: flex; gap: var(--space-6); flex-wrap: wrap">
      <span>全栈：<code>Nuxt 3 + Nitro</code></span>
      <span>服务端：<code>{{ backendFramework }}</code></span>
      <span>License: MIT</span>
    </div>
  </main>
</template>
