// fullstacks/next/src/app/login/page.tsx
"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useState, type FormEvent } from "react";
import { api } from "@/lib/api-client";
import { useAuthStore } from "@/stores/auth-store";
import { Alert } from "@/components/alert";
import { ApiError } from "@/types";

/**
 * 校验登录后跳转目标，防御 open redirect。
 *
 * 仅接受：以单 "/" 开头、第二字符不是 "/" 或 "\\" 的本地路径。
 * 拒绝示例：`//evil.example`、`/\evil.example`、`https://evil.example`、`javascript:...`
 *
 * 任何接受 ?next= 的实现都应该这样校验，而不是直接 router.replace(rawNext)。
 */
function safeNext(raw: string | null): string {
  const DEFAULT = "/me/created";
  if (!raw) return DEFAULT;
  if (raw.length < 2 || raw[0] !== "/") return DEFAULT;
  // 拒绝 //... 和 /\... — 浏览器会把它们当作 scheme-relative URL
  if (raw[1] === "/" || raw[1] === "\\") return DEFAULT;
  return raw;
}

function LoginInner() {
  const router = useRouter();
  const params = useSearchParams();
  const setSession = useAuthStore((s) => s.setSession);

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  async function submit(e: FormEvent) {
    e.preventDefault();
    setErr(null);
    setBusy(true);
    try {
      const tokens = await api.login({ email: email.trim(), password });
      setSession(tokens.user, tokens.accessToken, tokens.refreshToken);
      // 登录后默认跳「我创建的」（与 React 一致）；?next= 优先但**必须**
      // 经过 safeNext 校验，否则 ?next=//evil.example 会被浏览器解读为跨域跳转。
      router.replace(safeNext(params.get("next")));
    } catch (e) {
      setErr(e instanceof ApiError ? e.message : "登录失败");
    } finally {
      setBusy(false);
    }
  }

  return (
    <main
      className="cy-container cy-container--narrow"
      style={{ marginTop: "var(--space-12)", marginBottom: "var(--space-16)" }}
    >
      <div className="cy-card" style={{ maxWidth: 440, margin: "0 auto" }}>
        <h1
          style={{
            fontFamily: "var(--font-display)",
            fontSize: "var(--font-size-3xl)",
            margin: "0 0 var(--space-2)",
          }}
        >
          欢迎回来
        </h1>
        <p style={{ color: "var(--color-text-secondary)", margin: "0 0 var(--space-8)" }}>
          你留给未来的信，还在等你开启。
        </p>

        <form className="cy-form" onSubmit={submit}>
          <div className="cy-field">
            <label htmlFor="email">邮箱</label>
            <input
              className="cy-input"
              id="email"
              type="email"
              autoComplete="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>
          <div className="cy-field">
            <label htmlFor="pwd">密码</label>
            <input
              className="cy-input"
              id="pwd"
              type="password"
              autoComplete="current-password"
              required
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            <span className="cy-field__hint">忘记密码？M1 暂不支持找回，请联系管理员重置。</span>
          </div>

          <button
            className="cy-btn cy-btn--primary cy-btn--lg"
            type="submit"
            style={{ width: "100%" }}
            disabled={busy}
          >
            {busy ? "登录中…" : "登录"}
          </button>

          <div
            style={{
              textAlign: "center",
              color: "var(--color-text-muted)",
              fontSize: "var(--font-size-sm)",
            }}
          >
            还没有账号？
            <Link href="/register" style={{ color: "var(--color-brand-primary)" }}>
              立即注册
            </Link>
          </div>
        </form>
      </div>

      {err && (
        <div style={{ maxWidth: 440, margin: "var(--space-6) auto 0" }}>
          <Alert variant="danger">{err}</Alert>
        </div>
      )}
    </main>
  );
}

export default function LoginPage() {
  return (
    <Suspense
      fallback={
        <main className="cy-container" style={{ padding: "var(--space-10)" }}>
          加载…
        </main>
      }
    >
      <LoginInner />
    </Suspense>
  );
}

// fullstacks/nuxt/pages/login.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter, useRoute } from "vue-router";
import { api } from "@/api/client";
import { useAuthStore } from "@/stores/auth";
import { ApiError } from "@/types";
import Alert from "@/components/Alert.vue";

const router = useRouter();
const route = useRoute();
const auth = useAuthStore();

const email = ref("");
const password = ref("");
const busy = ref(false);
const err = ref<string | null>(null);

async function submit() {
  err.value = null;
  busy.value = true;
  try {
    const tokens = await api.login({ email: email.value.trim(), password: password.value });
    auth.setTokens(tokens);
    const from = (route.query.from as string | undefined) ?? "/me/created";
    router.replace(from);
  } catch (e) {
    err.value = e instanceof ApiError ? e.message : "登录失败";
  } finally {
    busy.value = false;
  }
}

useHead({ title: "登录" });
</script>

<template>
  <main
    class="cy-container cy-container--narrow"
    style="margin-top: var(--space-12); margin-bottom: var(--space-16)"
  >
    <div class="cy-card" style="max-width: 440px; margin: 0 auto">
      <h1 style="font-family: var(--font-display); font-size: var(--font-size-3xl); margin: 0 0 var(--space-2)">
        欢迎回来
      </h1>
      <p style="color: var(--color-text-secondary); margin: 0 0 var(--space-8)">
        你留给未来的信，还在等你开启。
      </p>

      <form class="cy-form" @submit.prevent="submit">
        <div class="cy-field">
          <label for="email">邮箱</label>
          <input
            id="email"
            v-model="email"
            class="cy-input"
            type="email"
            autocomplete="email"
            required
          />
        </div>
        <div class="cy-field">
          <label for="pwd">密码</label>
          <input
            id="pwd"
            v-model="password"
            class="cy-input"
            type="password"
            autocomplete="current-password"
            required
          />
          <span class="cy-field__hint">忘记密码？M1 暂不支持找回，请联系管理员重置。</span>
        </div>

        <button
          class="cy-btn cy-btn--primary cy-btn--lg"
          type="submit"
          style="width: 100%"
          :disabled="busy"
        >
          {{ busy ? "登录中…" : "登录" }}
        </button>

        <div
          style="text-align: center; color: var(--color-text-muted); font-size: var(--font-size-sm)"
        >
          还没有账号？
          <RouterLink to="/register" style="color: var(--color-brand-primary)">立即注册</RouterLink>
        </div>
      </form>
    </div>

    <div v-if="err" style="max-width: 440px; margin: var(--space-6) auto 0">
      <Alert variant="danger">{{ err }}</Alert>
    </div>
  </main>
</template>
